version: 2

project_name: wondertwin

builds:
  - id: wt
    main: ./cmd/wt
    binary: wt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: binaries
    ids:
      - wt
    formats:
      - binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
  - id: tarballs
    ids:
      - wt
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: wt
    ids:
      - tarballs
    repository:
      owner: wondertwin-ai
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: wondertwin-bot
      email: bot@wondertwin.ai
    directory: Formula
    homepage: https://wondertwin.dev
    description: "CLI for WonderTwin — behavioral twins for third-party APIs"
    license: MIT
    test: |
      system "#{bin}/wt", "version"
    install: |
      bin.install "wt"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
