version: 2
builds:
  - main: ./cmd/wt
    binary: wt
    env: [CGO_ENABLED=0]
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ldflags: -s -w -X main.version={{.Version}}
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: checksums.txt
