version: 2

project_name: wondertwin

builds:
  - id: wt
    main: ./cmd/wt
    binary: wt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

# TODO: move twin-* artifact builds into a separate goreleaser config/workflow.
archives:
  - id: binaries
    ids:
      - wt
    formats:
      - binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
