version: 2

project_name: "twin-{{ .Env.TWIN }}"

builds:
  - id: twin
    main: "./twin-{{ .Env.TWIN }}/cmd/twin-{{ .Env.TWIN }}/"
    binary: "twin-{{ .Env.TWIN }}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: binaries
    ids:
      - twin
    formats:
      - binary
    name_template: "twin-{{ .Env.TWIN }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: wondertwin-ai
    name: registry
  name_template: "twin-{{ .Env.TWIN }}-v{{ .Env.VERSION }}"
  draft: false
  prerelease: auto

snapshot:
  version_template: "{{ .Env.VERSION }}-next"

changelog:
  disable: true
